[package]
name = "rsdk-core"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json"] }
tokio = { version = "1", features = ["full"] }
